name: sortingvisualizer
description: A sorting visualizer app.
version: 1.0.0+1

environment:
  sdk: '>=3.0.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  provider: 
  flutter_bloc: 
  hydrated_bloc: 
  path_provider: 

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true