name: sortingvisualizer
description: A sorting visualizer app.
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  provider: 
  flutter_bloc: ^6.0.5
  hydrated_bloc: ^6.0.1
  path_provider: ^1.6.5

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true